### ISSUE TITLE
Document how to use this with an `AwsCdkConstructLibrary` projen project

### ISSUE THREAD

**Issue by blimmer** [mrgrain/jsii-struct-builder#104]
A common use-case for this package is using it with an [AWS CDK Construct Library](https://projen.io/awscdk-construct.html) with Projen. However, it's not immediately clear how to use it. The README shows `new ProjenStruct`, but it doesn't say where to write that code.

**Comment by mrgrain** [comment]
It goes into your `.projenrc.ts` file.
But point taken 😃
