### ISSUE TITLE
Bug: annotations getting excluded

### ISSUE THREAD

**Issue by lexGPT** [mrgrain/jsii-struct-builder#142]
I upgrade the package to the newest version 0.4.11 and the generated structs have annotations missing from projen struct mixins. 

Left is generated with the 0.4.11 version right is the 0.3.1 version
<img width="1262" alt="Screenshot 2023-07-12 at 13 41 05" src="https://github.com/mrgrain/jsii-struct-builder/assets/112618115/c052cfa2-04a6-4c79-b061-3f18c0fdcde7">
<img width="1232" alt="Screenshot 2023-07-12 at 13 41 23" src="https://github.com/mrgrain/jsii-struct-builder/assets/112618115/1c57b570-3741-404d-ab4a-79cff2d59ddc">

No changes made any changes to the underlying ProjenStruct

**Comment by mrgrain** [comment]
Yes, https://github.com/mrgrain/jsii-struct-builder/pull/64 removes the default tag for required properties because it does not make sense to have a default if it is required.

However you can re-enable the old behavior like this:

```ts
new ProjenStruct(project, {
  name: 'MyProjectOptions',
  outputFileOptions: {
    defaultTagsForRequiredProps: true,
  },
})
```

**Comment by lexGPT** [comment]
Ah check I will add the option. Without these default annotations `npx projen new` fails because it can't automatically find the required values for cdkVersion and name.

**Comment by mrgrain** [comment]
Oh dang 🤦🏻 , you are absolutely right! Let's revert the default again!

**Comment by mrgrain** [comment]
@blimmer FYI this will change back again with the next release

**Comment by mrgrain** [comment]
@lexGPT https://github.com/mrgrain/jsii-struct-builder/pull/158 implements a feature to explicitly remove `@default` doctags for required properties.

Expect a new minor release soon to remove `outputFileOptions.defaultTagsForRequiredProps`.
