### ISSUE TITLE
Docs: how to mixin from local file?

### ISSUE THREAD

**Issue by bestickley** [mrgrain/jsii-struct-builder#174]
Hi, thanks so much for this library! Has really helped [cdk-nextjs](https://github.com/jetbridge/cdk-nextjs) offer a flexible/customizable L3 construct to deploy Next.js on AWS.

Given the example from the docs:
```ts
new ProjenStruct(project, { name: 'MyProjectOptions' })
  .mixin(Struct.fromFqn('projen.typescript.TypeScriptProjectOptions'))
  .omit('sampleCode', 'projenrcTs', 'projenrcTsOptions');
```
How could I adjust this example to create a new interface from a local file like:
```ts
new ProjenStruct(project, { name: 'MyProjectOptions' })
  .mixin(Struct.fromLocal('./my/file/path/TypeScriptProjectOptions.ts'))
  .omit('sampleCode', 'projenrcTs', 'projenrcTsOptions');
```

**Comment by mrgrain** [comment]
I'm not sure that's possible. `jsii-struct-builder` is using a jsii assembly for reflection on existing interfaces. What you are suggesting is pointing to a raw TS file that could contain anything! Even if we assume that it's just an interface, we would now need to reflect on it and that's kind-of difficult.

Taking one step back, may I ask what you are trying to achieve with it?

**Comment by bestickley** [comment]
@mrgrain, ah I see. I didn't know this package relied on jsii assembly for reflection of existing interfaces. In cdk-nextjs project linked above, I'm exposing an `overrides` property on the props of the main construct: `Nextjs`. I'm using this package to create optional interfaces for CDK Prop types used like `FunctionProps`, `DistributionProps` etc so we don't have to use `any`. I'd also like to offer overrides for constructs created locally in this package like `NextjsBucketDeployment` which is is used in `NextjsServer` and `NextjsStaticAssets`. I didn't think I could use `Struct.fromFqn` to reference that construct so that's why I created this issue.

**Comment by mrgrain** [comment]
Hm, I see. So something you actually can do, is reference a FQN from the local assembly. E.g.: `Struct.fromFqn('cdk-nextjs. NextjsBucketDeployment')`. Only thing to consider is that there's a bootstrapping issue because you need the local `.jsii` to be already available. 🤔

**Comment by bestickley** [comment]
Oh I see. I thought `Struct.fromFqn` looked in node_modules so that wouldn't work. Yes, I would have a circular dependency issue :/

**Comment by bestickley** [comment]
Whoops, didn't mean to close.

**Comment by mrgrain** [comment]
> I thought Struct.fromFqn looked in node_modules so that wouldn't work

Haha yeah. I only implemented that recently: https://github.com/mrgrain/jsii-struct-builder/pull/159

**Comment by bestickley** [comment]
Haha, well I appreciate you implementing that! Any ideas on how to get around bootstrap issue?

**Comment by mrgrain** [comment]
> Any ideas on how to get around bootstrap issue?

You will have to run `projen compile` first, which unlike `projen build` doesn't do a `projen default` at the start.

**Comment by mrgrain** [comment]
Otherwise you could define _all_ your interfaces (even the manual ones) with `jsii-struct-builder`. That is possibly a bit annoying, but would give you a single source of thruth.

**Comment by bestickley** [comment]
@mrgrain, I think I'll try to modify the GitHub action to run `projen compile` first instead of just running `projen build`. Is there  a simple or documented way to do that?

Here is an example of our GitHub Action (failing because I need to run `projen compile` first): https://github.com/jetbridge/cdk-nextjs/actions/runs/7171276028/job/19525876169?pr=181

**Comment by mrgrain** [comment]
Not this specifically, but I reckon you could patch the workflow files directly using the low level API:

https://projen.io/escape-hatches.html#object-file-patches

**Comment by bestickley** [comment]
Worked perfectly. Thanks so much, @mrgrain!
