### ISSUE TITLE
Bug: mixin sets every property as experimental

### ISSUE THREAD

**Issue by lexGPT** [mrgrain/jsii-struct-builder#22]
Hello, First of love the library. Overriding projen properties is/was a pain point of ours. We set the new default properties by hand and even enforce some but having it reflected in the generated docs is hard. With this library it's easy thanks for that. 

Using it however I think I found a bug as every property in the generated Struct has the `@stability experimental` doc annotation attached to it. 

Using this code I'm trying to generate a new Struct extending from `projen.typescript.TypeScriptProjectOptions`. 
```typescript
export class NodeLibraryBlocProjenOptions extends ProjenStruct {
    constructor(project: typescript.TypeScriptProject, options?: ProjenStructOptions) {
        const defaultOptions: ProjenStructOptions = {
            name: 'NodeLibraryProjenOptions',
            filePath: './src/blocs/node-library/node-library.projen-options.ts',
        };
        super(project, { ...defaultOptions, ...options });
        this.mixin(Struct.fromFqn('projen.typescript.TypeScriptProjectOptions'));
    }
}
```

This generates this Struct and every property now has the `@stability experimental` tag.

```typescript
/**
 * NodeLibraryProjenOptions
 */
export interface NodeLibraryProjenOptions {
    /**
     * TypeScript version to use.
     * NOTE: Typescript is not semantically versioned and should remain on the
     * same minor, so we recommend using a `~` dependency (e.g. `~1.2.3`).
     * @default "latest"
     * @stability experimental
     */
    readonly typescriptVersion?: string;
    /**
     * The name of the development tsconfig.json file.
     * @default "tsconfig.dev.json"
     * @stability experimental
     */
    readonly tsconfigDevFile?: string;
    /**
     * Custom tsconfig options for the development tsconfig.json file (used for testing).
     * @default - use the production tsconfig options
     * @stability experimental
     */
    readonly tsconfigDev?: javascript.TypescriptConfigOptions;
    /**
     * Custom TSConfig.
     * @default - default options
     * @stability experimental
     */
    readonly tsconfig?: javascript.TypescriptConfigOptions;
```

 I can remove it for individual properties by manually setting the stability to undefined in an update function.

**Comment by mrgrain** [comment]
Fun times! Basically this is because your source (in this case projen) has marked everything as `experimental`.
Can you do a PR that add something like a `withStability` method to easily change the stability of all properties?
