### ISSUE TITLE
feat: support partial implementation

### ISSUE THREAD

**Issue by gradybarrett** [mrgrain/jsii-struct-builder#61]
First of all, this is fantastic. 👏 🚀 

I started messing around with this when it was the first iteration (before the rename), and I could have sworn that the first cut supported implementing a jsii interface as a TS Partial - make every property optional. I can't seem to get that same behavior with this new version. Have I just officially lost it, or did that behavior get dropped in the transition?

Here's an example of what I'm doing right now:

```typescript
new ProjenStruct(project, { name: "TokenAuthorizerProps" })
  .mixin(Struct.fromFqn("aws-cdk-lib.aws_apigateway.TokenAuthorizerProps"))
  .withoutDeprecated();
```

And I'd like that produced interface to have all mixed-in properties as optional.

**Comment by gradybarrett** [comment]
Never mind, I guess the `update[All]` interface is the way to accomplish that. 😄

**Comment by mrgrain** [comment]
> First of all, this is fantastic. 👏 🚀

Thank you kindly!

> I started messing around with this when it was the first iteration (before the rename), and I could have sworn that the first cut supported implementing a jsii interface as a TS Partial - make every property optional.

Honestly can't remember myself. The first version was very much an experiment. 😅 

> What do you think of providing a way to mark all mixed-in props as optional?

Yeah I'm down for these kind of helpers. `withoutDeprecated()` is similar, you could totally do this using `omit` or `filter`, but it's just easier. Send a PR and I'll get it merged.

**Comment by gradybarrett** [comment]
Cool! PR incoming shortly. Reopening so I can tie back to this issue.
