### ISSUE TITLE
Remove `default` from docstring when updating prop to be required

### ISSUE THREAD

**Issue by blimmer** [mrgrain/jsii-struct-builder#62]
For example:

```ts
requiredNodejsProps.mixin(
  Struct.fromFqn("aws-cdk-lib.aws_lambda_nodejs.NodejsFunctionProps")
    .withoutDeprecated()
    .update("description", { optional: false })
);
```

Leaves the docstring in the produced code:

```ts
/**
 * A description of the function.
 * @default - No description.
 * @stability stable
 */
readonly description: string;
```

If `optional: false`, I think we could assume this (`docs` param):

```ts
requiredNodejsProps.mixin(
  Struct.fromFqn("aws-cdk-lib.aws_lambda_nodejs.NodejsFunctionProps")
    .withoutDeprecated()
    .update("description", { optional: false, docs: { default: undefined } })
);
```

**Comment by mrgrain** [comment]
I consider `update` to be a low-level method. But we should have an `.required(string[])` helper that should do that.

Also the renderer should probably omit it as well.

**Comment by mrgrain** [comment]
@blimmer https://github.com/mrgrain/jsii-struct-builder/pull/158 implements a feature to explicitly remove `@default` doctags for required properties.

Expect a new minor release soon to remove `outputFileOptions.defaultTagsForRequiredProps` which was added to allow removing the doctag.
