### ISSUE TITLE
feat: should be able to chain

### ISSUE THREAD

**Issue by ahammond** [mrgrain/jsii-struct-builder#94]
`ProjenStruct` should superclass `Struct` enough that `ProjenStruct.mixin()` can receive a `ProjenStruct` as a param.
![Screen Shot 2023-05-25 at 1 22 28 PM](https://github.com/mrgrain/jsii-struct-builder/assets/445764/db57a978-0597-4994-b892-c7fd7c90132a)

**Comment by mrgrain** [comment]
Good idea! It works the other way around already. Should be easy.
